import time
from services.http_client import get_data_indicadores, get_data_earning_yield
from services.excel_exporter import salvar_em_excel_por_abas

empresas = [
    ["CGRA4", "Grazziotin"],
    ["BRAV3", "Brava Energia"],
    ["JHSF3", "JHSF Participações"],
    ["ODPV3", "Odontoprev"],
    ["SAPR4", "Sanepar"],
    ["TAEE4", "Taesa"],
    ["ISAE4", "ISA Energia Brasil"],
    ["WIZC3", "Wiz Co"],
    ["AMER3", "Americanas"],
    ["MGLU3", "Magazine Luiza"],
    ["WEGE3", "WEG"],
    ["SLCE3", "SLC Agrícola"],
    ["SBSP3", "Sabesp"],
    ["ASAI3", "Assaí Atacadista"],
    ["CPLE3", "Copel"],
    ["PCAR3", "Grupo Pão de Açúcar"],
    ["HYPE3", "Hypera"],
    ["B3SA3", "B3"],
    ["VALE3", "Vale"],
    ["ELET3", "Eletrobras"],
    ["PETR4", "Petrobras"],
    ["KLBN4", "Klabin"],
    ["QUAL3", "Qualicorp"],
    ["NTCO3", "Natura &Co"],
    ["STBP3", "Santos Brasil"],
    ["AZZA3", "AZZA 360 (Arezzo/Soma)"],
    ["VIVT3", "Vivo"],
    ["ABEV3", "Ambev"],
    ["EPAR3", "Embpar"],
    ["CTNM4", "Tecidos Norte de Minas"],
    ["USIM3", "Usiminas"],
    ["TASA3", "Taurus Armas"],
    ["PSSA3", "Porto Seguro"],
    ["PTBL3", "Portobello"],
    ["MRVE3", "MRV Engenharia"],
    ["LAVV3", "Lavvi"],
    ["TGMA3", "Tegma"],
    ["HBSA3", "Hidrovias do Brasil"],
    ["SEQL3", "Sequoia"],
    ["GFSA3", "Gafisa"],
    ["DASA3", "Dasa"],
    ["RCSL4", "Recrusul"],
    ["LWSA3", "LWSA"],
    ["DMVF3", "Varejo Farma"],
    ["CMIN3", "CSN Mineração"],
    ["ALUP3", "Alupar"],
    ["MBRF3", "Marfrig"],
    ["MNPR3", "Minupar"],
    ["UNIP6", "Unipar"],
    ["LIGT3", "Light"],
    ["GRND3", "Grendene"],
    ["SEER3", "Ser Educacional"],
    ["ANIM3", "Anima Holding"],
    ["LREN3", "Lojas Renner"],
    ["SHUL4", "Schulz"],
    ["MILS3", "Mills"],
    ["RENT3", "Localiza"],
    ["MOVI3", "Movida"],
    ["LJQQ3", "Lojas Quero-Quero"],
    ["PETZ3", "Petz"],
    ["ESPA3", "Espaçolaser"],
    ["CAMB3", "Cambucci"],
    ["VULC3", "Vulcabras"],
    ["TECN3", "Technos"],
    ["VIVA3", "Vivara"],
    ["CEDO4", "Cedo Têxtil"],
    ["PTNT4", "Petenatti"],
    ["TFCO4", "Track & Field"],
    ["UCAS3", "Unicasa"],
    ["SOJA3", "Boa Safra Sementes"],
    ["AGRO3", "BrasilAgro"],
    ["TESA3", "Terra Santa"],
    ["JALL3", "Jalles Machado"],
    ["SMTO3", "São Martinho"],
    ["CAML3", "Camil Alimentos"],
    ["MDIA3", "M. Dias Branco"],
    ["BRFS3", "BRF"],
    ["JBSS3", "JBS"],
    ["BEEF3", "Minerva"],
    ["CRFB3", "Carrefour Brasil"],
    ["GMAT3", "Grupo Mateus"],
    ["BOBR4", "Bombril"],
    ["CYRE3", "Cyrela"],
    ["HBRE3", "HBR Realty"],
    ["JPSA3", "Jereissati"],
    ["LOGG3", "LOG CP"],
    ["MULT3", "Multiplan"],
    ["SCAR3", "São Carlos"],
    ["SIMH3", "Simpar"],
    ["EUCA4", "Eucatex"],
    ["RANI4", "Irani"],
    ["SUZB3", "Suzano"],
    ["BRAP3", "Bradespar"],
    ["CSNA3", "Siderúrgica Nacional"],
    ["BRKM3", "Braskem"],
    ["MGEL4", "Mangels"],
    ["GOAU3", "Metalúrgica Gerdau"],
    ["GGBR3", "Gerdau"],
    ["ATOM3", "Atom"],
    ["OPCT3", "OceanPact"],
    ["CSAN3", "Cosan"],
    ["PRIO3", "PRIO"],
    ["VBBR3", "Vibra Energia"],
    ["RECV3", "PetroReconcavo"],
    ["UGPA3", "Ultrapar"],
    ["BLAU3", "Blau Farmacêutica"],
    ["PNVL3", "Panvel"],
    ["PGMN3", "Pague Menos"],
    ["OFSA3", "Ouro Fino Saúde Animal"],
    ["PFRM3", "Profarma"],
    ["RADL3", "Raia Drogasil"],
    ["AALR3", "Alliar"],
    ["FLRY3", "Fleury"],
    ["HAPV3", "Hapvida"],
    ["MATD3", "Hospital Mater Dei"],
    ["RDOR3", "Rede D'Or"],
    ["BMOB3", "Bemobi"],
    ["CASH3", "Méliuz"],
    ["NGRD3", "Neogrid"],
    ["TOTS3", "Totvs"],
    ["POSI3", "Positivo Tecnologia"],
    ["INTB3", "Intelbras"],
    ["AMBP3", "Ambipar"],
    ["CSMG3", "Copasa"],
    ["ORVR3", "Orizon"],
    ["CMIG4", "Cemig"],
    ["CLSC4", "Celesc"],
    ["CEEB3", "Coelba"],
    ["CPFE3", "CPFL Energia"],
    ["KEPL3", "Kepler Weber"],
    ["EMAE4", "Emae"],
    ["ENGI4", "Energisa"],
    ["ENEV3", "Eneva"],
    ["EGIE3", "Engie Brasil"],
    ["EQTL3", "Equatorial Energia"],
    ["NEOE3", "Neoenergia"],
    ["POMO4", "Marcopolo"],
    ["DIRR3", "Direcional Engenharia"],
    ["CURY3", "Cury Construtora"],
    ["AXIA3", "Axia Energia"],
    ["CXSE3", "Caixa Seguridade"],
    ["ALOS3", "ALLOS"],
    ["TIMS3", "TIM"],
    ["BBAS3", "Banco do Brasil"],
    ["BBDC4", "Bradesco"],
    ["ITUB4", "Itaú Unibanco"],
    ["SANB4", "Santander Brasil"],
    ["BPAC5", "BTG Pactual"],
    ["ITSA4", "Itaúsa"],
    ["ABCB4", "Banco ABC Brasil"],
    ["BMGB4", "Banco BMG"],
    ["PINE4", "Banco Pine"],
    ["BMEB4", "Banco Mercantil"]
]

empresas_teste = [["BMEB4", "Banco Mercantil"], ["PETR4", "PETROBRAS"], ["BBAS3", "Banco do Brasil"], ["ITSA4", "ITAUSA"]]

def main():
    resultados = {}

    for empresa in empresas_teste:
        ticker = empresa[0]
        nome = empresa[1]

        print(f"Buscando dados de {nome} ({ticker})...")
        data = get_data_earning_yield(ticker)

        if data is not None and not data.empty:
            resultados[ticker] = data
        else:
            print(f"Aviso: Não foi possível obter dados para {ticker}.")

        # Intervalo para evitar rate limit na API
        time.sleep(2)

    # Chamada do módulo de exportação isolado
    salvar_em_excel_por_abas(resultados, "outputs/indicadores_bolsa.xlsx")


if __name__ == "__main__":
    main()